name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version 16

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: DataSpoof/project_github_action
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Install dependencies and run model
        run: |
          pip install -r requirements.txt
          python train.py

      - name: Generate report and publish artifacts
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md

